CLIENT = root@carrot

# DO NOT CHANGE - DIYCOMPILE DEPENDS ON IT BEING HERE
INSTALL_PATH = /usr/bin

# IT'S INSTALLATION/REMOVAL CANNOT DEPEND ON ITSELF!
GIMME_PERM = 0

OS = 14.5
ARCH = arm64

GO_NAME = snoopy

include $(DIYCOMPILE)/diycompile.mk
